### ISSUE TITLE
CSS files not linking

### ISSUE THREAD

**Issue by pexeixv** [htmlpreview/htmlpreview.github.com#100]
When previewing an HTML file, only the HTML is shown without linking it to any CSS files.

**Comment by wom-bat** [comment]
This is because css is often fetched via the YACDN.ORG proxy, which no longer works.

**Comment by niutech** [comment]
YACDN is no longer being used.

**Comment by niutech** [comment]
YACDN is no longer being used.

**Comment by niutech** [comment]
YACDN is no longer being used.

**Comment by niutech** [comment]
YACDN is no longer being used.
