### ISSUE TITLE
Intradocument links (<a href="#foo"/>) don't work

### ISSUE THREAD

**Issue by martinthomson** [htmlpreview/htmlpreview.github.com#11]
(In Firefox, at least)

I think that this is because of the following code:

```
data.query.results.resources.content.replace(/<head>/i, '<head><base href="' + HTMLPreview.folder() + '">')
```

That should be relatively easy to fix by setting the base to the filename.

**Comment by barrydegraaff** [comment]
How did you change the base href? Code example please.
