### ISSUE TITLE
No definition found for Table data.headers

### ISSUE THREAD

**Issue by danielgtaylor** [htmlpreview/htmlpreview.github.com#16]
@niutech, seems all requests are currently broken with this response:

```
No definition found for Table data.headers
```

Example URL that is broken: http://htmlpreview.github.io/?https://raw.github.com/twbs/bootstrap/gh-pages/2.3.2/index.html

Using Mac OS 10.9.x, Chrome 33, not sure if you need anything else.

Any ideas?

**Comment by leocaseiro** [comment]
Hi I'm having this issue atm as well.

http://htmlpreview.github.io/?https://github.com/leocaseiro/angular-chosen/blob/master/example/index.html

**Comment by niutech** [comment]
This is because http://www.datatables.org is down.

**Comment by kenny-evitt** [comment]
I'm getting a pretty similar error "No definition found for Table headers"; example:

 - http://htmlpreview.github.io/?https://github.com/mccalltd/AttributeRouting/blob/gh-pages/index.html

**Comment by sargdavid** [comment]
I'm having same issue now (08/26/2017). If I keep refreshing the page, eventually, after 5-10 refreshes, it loads. The file is 1.3 MB in size, can that be a problem?

**Comment by ananyaojha** [comment]
I'm getting error like this :

<error xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" yahoo:lang="en-US">
<description>No definition found for Table data.headers</description>
</error>

Any idea why it's happening?

**Comment by ternsip** [comment]
Same issue
#ternsip/StructPro/issues/29

**Comment by niutech** [comment]
This is an issue at the YUI side, filed as yql/yql-tables#490
