### ISSUE TITLE
Not needed? rawgit.com works

### ISSUE THREAD

**Issue by tomByrer** [htmlpreview/htmlpreview.github.com#27]
eg: old:
http://htmlpreview.github.com/?http://github.com/dcodeIO/Preprocessor.js/master/docs/Preprocessor.html

> Error: Cannot load file http://raw.githubusercontent.com/dcodeIO/Preprocessor.js/master/docs/Preprocessor.html

new:
https://rawgit.com/dcodeIO/Preprocessor.js/master/docs/Preprocessor.html

**Comment by neothemachine** [comment]
So what's the advantage of HTMLPreview compared to rawgit? Only the fact that you theoretically can use your own proxy? I guess noone would do that anyway.

**Comment by niutech** [comment]
As I said, Rawgit is a third-party sever and if it was hacked, it could modify the source, or if it was down, you could not see anything. On the other hand, HTMLPreview uses the first-party Github infrastructure.

**Comment by neothemachine** [comment]
Well, although not likely, YGL/Yahoo could be hacked as well. But yes, I see the point.
