### ISSUE TITLE
Mixed content errors prevent content loading

### ISSUE THREAD

**Issue by josiahcarlson** [htmlpreview/htmlpreview.github.com#32]
Github content is served over https, as is htmlpreview, but the part that discovers javascript/css via the Yahoo API is loading via http - leading to mixed content errors and a failure to load the preview in Chrome and Firefox. IE 11 will prompt for whether you want to load the insecure content.

**Comment by dhimmel** [comment]
+1, until then I'm sticking with https://rawgit.com/
