### ISSUE TITLE
Removal of Google ads

### ISSUE THREAD

**Issue by Lekensteyn** [htmlpreview/htmlpreview.github.com#33]
Hi,

While looking for a service that displays the contents for gists, I found your project. Since commit 136b43a7007ae5e0cdc7ea11e71c1ff2e0fbe03e, Google ads were injected in the landing page. Why were these added?

Can you add it (in the spirit of a public service, hosted by Github)?

**Comment by niutech** [comment]
Google Ads are there for monetization of my work. I don't see anything wrong with them. You don't have to click them.

**Comment by Lekensteyn** [comment]
So you were aware of it (the author that introduced the change is `= <=>` which looked a bit strange).

Plenty of alternatives that are more reliable than your "work", for example https://github.com/rgrove/rawgit.

https://rawgit.com/twbs/bootstrap/gh-pages/2.3.2/index.html

**Comment by niutech** [comment]
I removed the ads.
