### ISSUE TITLE
Autofocus

### ISSUE THREAD

**Issue by szepeviktor** [htmlpreview/htmlpreview.github.com#35]
Could you spare everyone 1 click?
https://github.com/htmlpreview/htmlpreview.github.com/blob/master/index.html#L51
`autofocus`

Thank you!

**Comment by niutech** [comment]
Fixed.

**Comment by szepeviktor** [comment]
Thanks.
https://github.com/htmlpreview/htmlpreview.github.com/commit/296f172523a041f2452c60f31546f445169bb3da#diff-eacf331f0ffc35d4b482f1d15a887d3bR36
