### ISSUE TITLE
Loaded local script files don't load from the right location

### ISSUE THREAD

**Issue by fresheneesz** [htmlpreview/htmlpreview.github.com#37]
If the html file has something like `<script src="proto.umd.js"></script>`, htmlpreview attempts to load proto.umd.js from its own domain, rather than from github.

**Comment by niutech** [comment]
Does it? HTMLPreview adds `<base href="https://raw.githubusercontent.com/[user]/[project]/[branch]/">` to the `<head>`, so the script with a relative URL should be loaded from that base folder. Could you give me a counterexample?
