### ISSUE TITLE
Cannot load html from rmarkdown

### ISSUE THREAD

**Issue by mdehollander** [htmlpreview/htmlpreview.github.com#39]
Hi,

I am not able to load a html generated with rmarkdown:
https://htmlpreview.github.io/?https://gitlab.com/mdehollander/biosb2016/raw/master/biosb2016.html

However, a file made by someone else using the same method works:
https://htmlpreview.github.io/?https://raw.githubusercontent.com/psu-psychology/neuro-521/master/neuro-521-gilmore-2016-01-12.html

Other html code hosted externally on gitlab for example works as well:
https://htmlpreview.github.io/?https://gitlab.com/oliver-salzburg/angular-timepicker/raw/master/demo.html

Any clue what is wrong with my html file?

**Comment by niutech** [comment]
It's because you have to sign in to Gitlab in order to see your HTML document.

**Comment by mdehollander** [comment]
Sorry, I had to close the repository. When I make a Hello World test with the Rstudio rmarkdown ioslides templates it works: 

http://htmlpreview.github.io/?https://gitlab.bioinf.nioo.knaw.nl/MattiasH/rmarkdown-ioslides/raw/master/helloworld.html

So there is something in my previous slides blocking it. I will start debugging from there....
