### ISSUE TITLE
Scripts are run twice

### ISSUE THREAD

**Issue by CarlsonL** [htmlpreview/htmlpreview.github.com#40]
I've been using github to host exercises I've completed for my programming class, and htmlpreview to display the output.

But in files that use a &lt;script&gt; tag, everything inside the tag is executed twice:
https://htmlpreview.github.io/?https://github.com/CarlsonL/Web-Programming-2016/blob/master/Exercise7-16.html

Other than this issue, I've found the site very useful.

**Comment by niutech** [comment]
Fixed.
