### ISSUE TITLE
Everything seems broken

### ISSUE THREAD

**Issue by dotnetchris** [htmlpreview/htmlpreview.github.com#41]
http://htmlpreview.github.io/?https://raw.github.com/twbs/bootstrap/gh-pages/2.3.2/index.html

> http://query.yahooapis.com/v1/public/yql?q=use%20%22https%3A%2F%2Fraw.githubusercontent.com%2Fyql%2Fyql-tables%2Fmaster%2Fdata%2Fdata.headers.xml%22%20as%20headers%3B%20select%20*%20from%20headers%20where%20url%3D%22https%3A%2F%2Fraw.github.com%2Ftwbs%2Fbootstrap%2Fgh-pages%2F2.3.2%2Findex.html%22&format=json&diagnostics=true&callback=HTMLPreview.loadHTML

responded with a status of 502 (Connection refused)

**Comment by niutech** [comment]
It works for me, apart from CSS styles due to the error: Resource
interpreted as Stylesheet but transferred with MIME type text/plain.

**Comment by dotnetchris** [comment]
Seems like it was a temporary outage of yahooapis
