### ISSUE TITLE
Refused to execute script "" because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by dotnetchris** [htmlpreview/htmlpreview.github.com#42]
I think this project needs to leverage https://rawgit.com/ so that you can actually get proper mime types back

**Comment by aronatkins** [comment]
This also applies for linked CSS files and SVG.

**Comment by niutech** [comment]
The aim of this project is not to rely on some third-party servers (except YQL run by Yahoo, which are trustworthy) and render HTML documents on client side.

**Comment by aronatkins** [comment]
@niutech It's possible that the solution (rawgit) is not correct but the MIME type problem is real.

Consider an index.html containing:
```
<link rel="stylesheet" href="style.css">
```

Place both the index.html and CSS files inside a GitHub repository and try to view those files through htmlpreview. You'll get complaints about the MIME type of style.css. raw.githubusercontent.com returns a response header `Content-Type: text/plain; charset=utf-8`.

The same issue happens for SVG; they are returned as `text/plain` and aren't rendered (JPG work fine).
