### ISSUE TITLE
Preview works often only after 1 or 2 manual reloads

### ISSUE THREAD

**Issue by de-jcup** [htmlpreview/htmlpreview.github.com#47]
With 
- Firefox (Linux Version 49.0)
- Chrome/HTMLView (Android 5.1.1)
- Edge (Windows10)
- Chrome (Windows 10)
  
  you often get no preview but instead  a "No definition found for Table headers" as output. You need 1 or 2 reloads (F5...) to get the real previews opened. 

I had this problem in the last 24 hours very often
Examples:
- http://htmlpreview.github.io/?https://github.com/twbs/bootstrap/gh-pages/2.3.2/index.html 
- http://htmlpreview.github.io/?https://github.com/de-jcup/egradle/blob/master/egradle-plugin-main/html/toc.html

**Comment by grchannels** [comment]
Try rawgit.com until this problem be solved.

**Comment by de-jcup** [comment]
Thank you :-)

**Comment by ptfmiller** [comment]
Just wanted to note I'm having this problem as well. Using safari to view http://htmlpreview.github.io/?https://github.com/ptfmiller/concept-md/blob/master/ex.html

I will be using rawgit.com when necessary.

**Comment by npgall** [comment]
Same here. I was using htmlpreview to serve JavaDocs for my project, but it is not working anymore.
http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/index.html

**Comment by niutech** [comment]
The URLs are working for me now, although it may be related to #54.
