### ISSUE TITLE
script files linked below the body are not shown

### ISSUE THREAD

**Issue by wiwum** [htmlpreview/htmlpreview.github.com#51]
I have my script filed linked below the body element and when you inspect the HTML of my page through this project the links just aren't there

**Comment by wiwum** [comment]
I put my <script> tags in my body and now it work but you still might want to look into this.
Also great project I'll be using this a lot I think.

**Comment by niutech** [comment]
Thank you. However, putting any element below `</body>` is against the HTML standard and it is not supported at the moment.
