### ISSUE TITLE
Error: Cannot load file 

### ISSUE THREAD

**Issue by nelsonswork** [htmlpreview/htmlpreview.github.com#52]
Can not preview my html file I get the following issue. Error: Cannot load file http://htmlpreview.github.io/?https://github.com/username/filepath/filename

**Comment by mhucka** [comment]
Is it a private repo? I think this system doesn't work if the repo is private. (I have the same problem.)

**Comment by niutech** [comment]
The repo must be public in order for HTML Preview to work.

**Comment by joelostblom** [comment]
HTML Preview also works on private links as long as they include the token as mentioned in #80.
