### ISSUE TITLE
No definition found for Table headers

### ISSUE THREAD

**Issue by xushell** [htmlpreview/htmlpreview.github.com#54]
Having this issue with my preview:

https://htmlpreview.github.io/?https://github.com/xushell/FashionUniverse6/blob/master/index.html#

Is there a fix for this?

**Comment by Thornus** [comment]
Happens with my preview too!

**Comment by sargdavid** [comment]
I'm having same issue now (08/26/2017). If I keep refreshing the page, eventually, after 5-10 refreshes, it loads. The file is 1.3 MB in size, can that be a problem?

**Comment by rknenuvis** [comment]
I got the same  problems .please fix it soon

**Comment by zjgyb** [comment]
I also got the samequestions.

**Comment by RoamIn** [comment]
me too.

**Comment by rknenuvis** [comment]
Sorry,is there a fix for this? I taked apart in a competition using demo on this, now it doesn't work. I am so worried.Please fix it.  TTTTTThank you  so much!

**Comment by niutech** [comment]
Sorry for replying late. This is the YQL issue filed as yql/yql-tables#490.
