### ISSUE TITLE
Paths problem

### ISSUE THREAD

**Issue by AndrewHani** [htmlpreview/htmlpreview.github.com#55]
In the preview of my repository https://github.com/AndrewHani/CairoGuide, it can't access not the css file nor the js, although it's well connected on my local text editor.

Thank you.

**Comment by niutech** [comment]
You have capitalization issues in URLs referenced in Home.html, e.g. `Js` instead of `JS` or `css` instead of `CSS`. Keep in mind that GitHub is case-sensitive.

**Comment by AndrewHani** [comment]
Thank you..

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
