### ISSUE TITLE
I couldn't preview my application. The htmlpreview supports React?

### ISSUE THREAD

**Issue by daniellycosta** [htmlpreview/htmlpreview.github.com#56]
I generated the link on the site ([LINK HERE!](https://htmlpreview.github.io/?https://github.com/daniellycosta/LearningWebDevelopment/blob/master/React/First_Exercise_React_Course.html)) but nothing happens and I only see a blank page.

**Comment by niutech** [comment]
The reason is `Uncaught SyntaxError: Unexpected token <` - you have JSX code included in `<script>` and HTMLPreview does not support JSX, only vanilla JS. You can transcode JSX to JS using Babel.

**Comment by daniellycosta** [comment]
Thank you! I'm going to try

**Comment by uetoyo** [comment]
I have a similar problem with modules:
```
SyntaxError: import declarations may only appear at top level of a module.
```

**Comment by niutech** [comment]
You cannot use ES6 `import` in functions and this polyfill is wrapping the code in an anonymous function. So it will not work.
