### ISSUE TITLE
I cannot preview my code

### ISSUE THREAD

**Issue by tejanhu** [htmlpreview/htmlpreview.github.com#58]
Hi 

I am new to using htmlpreview.github.io, and I am finding it rather difficult to preview: https://github.com/tejanhu/Vue-Postal-Code-Lookup-API.

I am receiving the following error whenever I prepend the url: 
Error: Cannot load file https://raw.githubusercontent.com/tejanhu/Vue-Postal-Code-Lookup-API

Please advise.

**Comment by niutech** [comment]
You have to paste the URL of the HTML document, not the repository, i.e. https://htmlpreview.github.io/?https://github.com/tejanhu/Vue-Postal-Code-Lookup-API/blob/master/end.html
