### ISSUE TITLE
This script is so useful!

### ISSUE THREAD

**Issue by inglesuniversal** [htmlpreview/htmlpreview.github.com#61]
How come it is not publicly promoted on GitHub?

**Comment by niutech** [comment]
Thank you! How would you like to promote it?

**Comment by inglesuniversal** [comment]
well users from sites like CodePen would love to have access to something like this... I would speed up their work by 100% at least. KUDOS!!!!

**Comment by niutech** [comment]
Don't they have access to https://htmlpreview.github.io? Thanks anyway!

**Comment by inglesuniversal** [comment]
Some might, but I would say that a lot a people don't even know that it even exists!
