### ISSUE TITLE
Error loading page due to poor network connectivity?

### ISSUE THREAD

**Issue by kgashok** [htmlpreview/htmlpreview.github.com#65]
For the link https://htmlpreview.github.io/?https://github.com/kgisl/cs8251/blob/master/notes/unit5.html#unit-v-file-processing, in the console I noticed this: 

![screenshot 2019-01-04 at 07 45 07](https://user-images.githubusercontent.com/2399010/50670961-d0bd1400-0ff4-11e9-978c-e32da9437312.png)

**Comment by rgetz** [comment]
any comments from the developers? @niutech ?

**Comment by rgetz** [comment]
For anyone interested - https://raw.githack.com/ is functional.

but is not a client side solution, so you need to be careful about bandwidth.

**Comment by niutech** [comment]
It should be fixed by not, although there are still some known issues in the latest version, which will be fixed.

As for Githack, it uses server-side processing, unlike HTMLPreview, which works client-side.

**Comment by rgetz** [comment]
@niutech - thanks. Know you are working on things, thanks for your effort 

https://htmlpreview.github.io/?https://github.com/analogdevicesinc/buildroot/blob/pluto/board/pluto/msd/index.html 

Still seems to be broken. I won't open a new issues - I assume you are working through things.
