### ISSUE TITLE
Failure to load Yahoo Query means this software no longer works

### ISSUE THREAD

**Issue by scottcwilson** [htmlpreview/htmlpreview.github.com#66]
All links using http://htmlpreview.github.io/ 
simply show "Loading...". 

See end of life notice on YQL at 
https://developer.yahoo.com/yql/?guccounter=1

**Comment by petervannes** [comment]
+1 for me. 

Console logging shows, inhibiting any github content to preview.

http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20data.headers%20where%20url%3D%22https%3A%2F%2Fraw.githubusercontent.com%2Fpetervannes%2FLandjeRobot%2Fmaster%2FGuides%2FStudent%2520guide%2520NLD.html%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&diagnostics=true&callback=HTMLPreview.loadHTML
Failed to load resource: A server with the specified hostname could not be found.

**Comment by niutech** [comment]
Indeed, I am working on update, it will work similar to my [X-Frame-Bypass](https://github.com/niutech/x-frame-bypass) web component.

**Comment by scottcwilson** [comment]
Thank you for your hard work on this.  It's an essential component for me!

**Comment by niutech** [comment]
Thanks! I have just rewritten HTMLPreview to use one of the free CORS proxies instead of now defunct YQL. It's still not finished and I will fix it.
