### ISSUE TITLE
CORS proxy https://crossorigin.me

### ISSUE THREAD

**Issue by danielweck** [htmlpreview/htmlpreview.github.com#73]
Suggestion - add `https://corsproxy.github.io` to:

https://github.com/htmlpreview/htmlpreview.github.com/blob/102c5845ae35e2fab7ac0aff4ca9b7d9f511a07b/htmlpreview.js#L90-L94

**Comment by danielweck** [comment]
Note: `https://crossorigin.me` is the old URL which now redirects to `https://corsproxy.github.io`

**Comment by niutech** [comment]
The service does no longer work.
