### ISSUE TITLE
htmlpreview is not working for my html file

### ISSUE THREAD

**Issue by hosseinmoein** [htmlpreview/htmlpreview.github.com#79]
my html file:
https://github.com/hosseinmoein/DataFrame/blob/Hossein/DocTest/docs/DataFrameDoc.html

Regards,
Hossein Moein

**Comment by niutech** [comment]
The original URL does not exist, but this URL works: https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/DataFrame.html
