### ISSUE TITLE
Incorrect toc hyperlink to subsections in Chrome and Safari

### ISSUE THREAD

**Issue by fursham-h** [htmlpreview/htmlpreview.github.com#81]
I've been getting errors upon clicking on the toc hyperlinks to a different subsection. I soon realize that the formatting of the hyperlink text contain a 'hyphen' where a period be at. This error occurs in chrome and safari browsers, but works fine with firefox. 

I've rendered a test html using rmarkdown (https://htmlpreview.github.io/?https://github.com/fursham-h/factR/blob/master/vignettes/test.html). 
I've copied the hyperlink to the first heading here (https://htmlpreview-github-io/?https://github-com/fursham-h/factR/blob/master/vignettes/test-html#heading1)

**Comment by niutech** [comment]
Sorry for the late answer. Your URL is invalid, but I have checked https://htmlpreview.github.io/?https://github.com/fursham-h/factR/blob/master/vignettes/factR.html#getting-started and it successfully scrolls to the Getting Started chapter.
