### ISSUE TITLE
Blank Screen on Preview

### ISSUE THREAD

**Issue by VismayaAtreya** [htmlpreview/htmlpreview.github.com#89]
When I preview my HTML file, I get a blank screen. Even the title remains as 'https://htmlpreview.github.io....'. It uses the bootstrap templates and that included CSS files. My HTML file link is : https://github.com/VismayaAtreya/Website/blob/master/Vismaya%20Ateya/contact/features.html and my preview link is : https://github.com/VismayaAtreya/Website/blob/master/Vismaya%20Ateya/contact/features.html

Thanks in advance!

**Comment by niutech** [comment]
Sorry, but your links give error 404 _Page not found_. The best solution for you is to use [Github Pages](https://pages.github.com/).

**Comment by VismayaAtreya** [comment]
Thanks! I did that! It works great!

**Comment by VismayaAtreya** [comment]
Still, when I use htmlpreview to view the html files, I still get a blank screen. When I remove the CSS files, htmlpreview works!
