### ISSUE TITLE
<hr> tags not showing up?

### ISSUE THREAD

**Issue by veltaine** [htmlpreview/htmlpreview.github.com#91]
Sorry if this was resolved, but for some reason having <hr> tags with a custom CSS don't show up on the preview page.

I tested with my IDE (VScode) and also put the code on codepen.io and they both display the lines, but on the previewer, the page doesn't display them, and they are removed in the webpage's code as well, but the repository still has them.

**Comment by niutech** [comment]
Could you please provide the URL to your page?

**Comment by veltaine** [comment]
Sure, though I seem to be having bigger issues than that (though they seem to be showing up now)

https://htmlpreview.github.io/?https://github.com/veltaine/technicalDocumentation/blob/master/index.html

I am likely going to chalk this up to something on my end, and will update if I'm able to replicate the same error as before.  Thank you for following up!
