### ISSUE TITLE
get error code 429 when using html preview

### ISSUE THREAD

**Issue by pranavkirtani88** [htmlpreview/htmlpreview.github.com#92]
I get error code 429 sometimes when I use https://htmlpreview.github.io/?https://github.com/persistentsystems/corda-did-method/blob/master/corda_did_method.html

**Comment by fionarhuang** [comment]
I have the same issue too (https://htmlpreview.github.io/?https://github.com/fionarhuang/treeclimbR_article/blob/master/microbe/docs/3-Visualization.html)

**Comment by niutech** [comment]
HTML Preview uses https://jsonp.afeld.me or https://cors-anywhere.herokuapp.com under the hood. The former returns 403 Forbidden (see https://github.com/afeld/jsonp/issues/179) and the latter sometimes returns 429 Too Many Requests. You have to retry.

**Comment by alshan** [comment]
The service consistently returns status 429 for at least 8 hours now.
https://htmlpreview.github.io/?https://raw.githubusercontent.com/JetBrains/lets-plot-kotlin/master/docs/api-reference/plot-api/index.html

**Comment by niutech** [comment]
This issue is still opened. I have filed the issue: https://github.com/Rob--W/cors-anywhere/issues/283 and I have added fallback proxies. Check if the problem remains.

**Comment by fionarhuang** [comment]
> This issue is still opened. I have filed the issue: https://github.com/Rob--W/cors-anywhere/issues/283 and I have added fallback proxies. Check if the problem remains.

It works for me now! Thanks!

**Comment by niutech** [comment]
That's great! If you know any other reliable and free CORS proxy, please suggest it.
