### ISSUE TITLE
htmlpreview is extremely slow 

### ISSUE THREAD

**Issue by hosseinmoein** [htmlpreview/htmlpreview.github.com#93]
I use htmlpreview to render HTML documents for my codebase. Since Friday last, htmlpreview has been extremely slow. It takes up to a minute  to fetch documents.
Is that a know problem?

Best,
HM

**Comment by hosseinmoein** [comment]
I am now getting this error
```
Error: Cannot load https://raw.githubusercontent.com/hosseinmoein/DataFrame/master/docs/HTML/DataFrame.html: 429 Too Many Requests
```

This used to work lawlessly for a long time

**Comment by niutech** [comment]
This error comes from https://cors-anywhere.herokuapp.com. If you know any other working CORS proxy, please suggest.

**Comment by hosseinmoein** [comment]
Thanks.
Do you know why this has been happening in the past few days?
Is there a fix in the works?


Best,
HM

**Comment by niutech** [comment]
Yes, I have fixed CORS proxies, now it should get back to normal.
