### ISSUE TITLE
Error 429 persists

### ISSUE THREAD

**Issue by sjspielman** [htmlpreview/htmlpreview.github.com#94]
Hello, 

Since yesterday, previews have not been loading (intermittently works, but not most of the time) due to the 429 error. Is there a fix coming for this soon?

Thanks, 
Stephanie

**Comment by niutech** [comment]
This is a problem with CORS Anywhere, I have submittes the issue: https://github.com/Rob--W/cors-anywhere/issues/283
Meanwhile I have added fallback proxies, so it should work now.
