### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by TrianguloY** [htmlpreview/htmlpreview.github.com#95]
When trying to fix the CORS error a few days ago, you made a change in the fetching code so now pages are fetched using fetch instead of fetchProxy.
https://github.com/htmlpreview/htmlpreview.github.com/commit/adaa08ac90758703e6294003b5a24a0e74286e17?branch=adaa08ac90758703e6294003b5a24a0e74286e17&diff=unified#diff-0f292e46fc1906eacb3fdbdaced082678d3b8d83fb44ab79b927d2abd836c358L107

Now, when using a page which has cors disabled, like dropbox, the service doesn't work.
http://htmlpreview.github.io/?https://www.dropbox.com/s/mgw65rktedx4pjl/Hello%20world.html?raw=1

Was that change a forgotten invalid fix? I recommend using fetchProxy again, so that dropbox links (and others) works again.

**Comment by niutech** [comment]
This change was meant to lower the usage of CORS proxies and improve loading time, so that HTML documents from https://raw.githubusercontent.com could be fetched directly. I didn't realize that HTMLPreview is used outside of GitHub/Bitbucket, like with Dropbox. I will make an exception for such cases.

**Comment by TrianguloY** [comment]
Ah, I understand.

Yes, a friend of mine uses the page with dropbox (https://jdelcastilloshideout.blogspot.com/2020/09/paravicini-y-la-roca-rodante.html) and asked me why the page stopped working, so I investigated and found the issue.

Thanks for the quick reply 😊. An exception is enough for my friend.

**Comment by TrianguloY** [comment]
Sorry for the reply, but perhaps you have disabled notifications of pull requests.
I investigated the issue and found a solution that also should drastically reduce the number of petitions to the cors proxies. More info in the pull request: https://github.com/htmlpreview/htmlpreview.github.com/pull/96

You can check the result here:
https://trianguloy.github.io/htmlpreview.github.com/?https://www.dropbox.com/s/mgw65rktedx4pjl/Hello%32world.html?raw=1
https://trianguloy.github.io/htmlpreview.github.com/?https://github.com/twbs/bootstrap/gh-pages/2.3.2/index.html
https://trianguloy.github.io/htmlpreview.github.com/?https://github.com/documentcloud/backbone/blob/master/examples/todos/index.html

**Comment by peastman** [comment]
I also started encountering this error, but my file is on Github.  Here's the file:

https://github.com/openmm/pdbfixer/blob/master/Manual.html

The following link produces the error message given above:

https://htmlpreview.github.io/?https://github.com/openmm/pdbfixer/blob/master/Manual.html

**Comment by peastman** [comment]
Is there anything I can do to work around this problem?

**Comment by TrianguloY** [comment]
@peastman The link you posted above (https://htmlpreview.github.io/?https://github.com/openmm/pdbfixer/blob/master/Manual.html) works fine for me. I checked the mentioned issue from your repo and the link is different. Simply update the link to this one and it will work again.
